import json
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent
TARGET = BASE_DIR / "assets" / "data" / "ensaglamdata_with_example_tr.json"
WIKI = BASE_DIR / "assets" / "data" / "WIKI_MERGED_5000_CORRECTED.json"
FULL = BASE_DIR / "assets" / "data" / "wordfarm_full_with_examples.json"
NEEDED = 1000


def load_json(path: Path):
    with path.open("r", encoding="utf-8") as f:
        return json.load(f)


def cefr_for(word: str) -> str:
    length = len(word)
    if length <= 4:
        return "A2"
    if length <= 6:
        return "B1"
    if length <= 8:
        return "B2"
    if length <= 10:
        return "C1"
    return "C2"


EX_TEMPLATES_EN = [
    "She explained the word '{word}' during class.",
    "We discussed how to use '{word}' in a sentence.",
    "He looked up '{word}' to be sure about its meaning.",
    "The article mentioned '{word}' several times.",
    "They practiced pronouncing '{word}' correctly.",
]

EX_TEMPLATES_TR = [
    "Derste '{word_tr}' kelimesinin anlamını açıkladı.",
    "'{word_tr}' kelimesini bir cümlede nasıl kullanacağımızı tartıştık.",
    "Anlamından emin olmak için '{word_tr}' kelimesine baktı.",
    "Makale '{word_tr}' kelimesinden birkaç kez bahsetti.",
    "'{word_tr}' kelimesini doğru telaffuz etmeyi çalıştılar.",
]

MANUAL_BANK = [
    ("abide", "uymak"),
    ("abolish", "yürürlükten kaldırmak"),
    ("abrupt", "ani"),
    ("abundance", "bolluk"),
    ("acclaim", "övgü"),
    ("acclimate", "alışmak"),
    ("accolade", "ödül"),
    ("accountable", "sorumlu"),
    ("accrue", "birikmek"),
    ("acquaint", "tanıştırmak"),
    ("acquit", "beraat ettirmek"),
    ("acumen", "zeka"),
    ("adept", "usta"),
    ("adhere", "yapışmak"),
    ("adorn", "süslemek"),
    ("advent", "geliş"),
    ("adversary", "rakip"),
    ("advocate", "savunmak"),
    ("aerial", "havadaki"),
    ("aesthetic", "estetik"),
    ("affable", "dostça"),
    ("afflict", "eziyet etmek"),
    ("affluent", "varlıklı"),
    ("afloat", "su üstünde"),
    ("agitate", "çalkalamak"),
    ("ailment", "rahatsızlık"),
    ("airtight", "hava geçirmez"),
    ("alias", "takma ad"),
    ("allay", "yatıştırmak"),
    ("alleviate", "hafifletmek"),
    ("allocate", "tahsis etmek"),
    ("allude", "ima etmek"),
    ("altercation", "tartışma"),
    ("altruistic", "fedakar"),
    ("amass", "toplamak"),
    ("amenity", "konfor"),
    ("amiable", "cana yakın"),
    ("amplify", "güçlendirmek"),
    ("amulet", "muska"),
    ("analog", "benzer"),
    ("anecdote", "anekdot"),
    ("animate", "canlandırmak"),
    ("annex", "eklemek"),
    ("antidote", "panzehir"),
    ("apathy", "ilgisizlik"),
    ("appall", "dehşete düşürmek"),
    ("appease", "yatıştırmak"),
    ("applaud", "alkışlamak"),
    ("appraise", "değer biçmek"),
    ("apprehend", "tutuklamak"),
    ("aptitude", "yatkınlık"),
    ("arbiter", "hakem"),
    ("arcane", "esrarengiz"),
    ("ardent", "ateşli"),
    ("arduous", "zahmetli"),
    ("arsenal", "cephanelik"),
    ("articulate", "açık ifade etmek"),
    ("ascertain", "tespit etmek"),
    ("ascribe", "atfetmek"),
    ("assent", "onaylamak"),
    ("assertive", "kendinden emin"),
    ("assiduous", "gayretli"),
    ("assortment", "çeşit"),
    ("astute", "zeki"),
    ("attainable", "erişilebilir"),
    ("audible", "duyulabilir"),
    ("augment", "artırmak"),
    ("authenticity", "özgünlük"),
    ("avid", "hevesli"),
    ("aversion", "tiksinti"),
    ("awe", "hayranlık"),
    ("awkwardness", "sakarlık"),
    ("babble", "gevezelik etmek"),
    ("backbone", "omurga"),
    ("backlog", "birikmiş iş"),
    ("backtrack", "geri dönmek"),
    ("baffle", "şaşırtmak"),
    ("bailout", "kurtarma paketi"),
    ("ballast", "destek malzemesi"),
    ("banish", "sürgün etmek"),
    ("banter", "şakalaşmak"),
    ("barbaric", "vahşi"),
    ("bare", "çıplak"),
    ("barren", "verimsiz"),
    ("bashful", "utangaç"),
    ("bask", "güneşlenmek"),
    ("beacon", "fener"),
    ("befriend", "arkadaş olmak"),
    ("beggar", "dilenci"),
    ("behold", "seyretmek"),
    ("believable", "inanılır"),
    ("benefactor", "hayırsever"),
    ("benevolent", "iyiliksever"),
    ("benign", "iyi huylu"),
    ("bequeath", "miras bırakmak"),
    ("berth", "yatak yeri"),
    ("bewilder", "afallatmak"),
    ("biased", "önyargılı"),
    ("bibliography", "kaynakça"),
    ("bilateral", "iki taraflı"),
    ("bilingual", "iki dilli"),
    ("binge", "aşırı tüketmek"),
    ("biopsy", "biyopsi"),
    ("biotechnology", "biyoteknoloji"),
    ("bizarre", "tuhaf"),
    ("bland", "tatsız"),
    ("blemish", "leke"),
    ("blend", "karıştırmak"),
    ("blissful", "çok mutlu"),
    ("blockade", "abluka"),
    ("blunder", "gaf yapmak"),
    ("boastful", "övüngen"),
    ("bodyguard", "koruma"),
    ("boisterous", "gürültücü"),
    ("bolster", "desteklemek"),
    ("bombard", "bombalamak"),
    ("bondage", "esaret"),
    ("boon", "nimet"),
    ("boredom", "can sıkıntısı"),
    ("bounty", "ödül"),
    ("brace", "desteklemek"),
    ("bramble", "dikenli çalı"),
    ("brandish", "savurmak"),
    ("bravely", "cesurca"),
    ("brawl", "kavga etmek"),
    ("breadth", "genişlik"),
    ("breathtaking", "nefes kesici"),
    ("brew", "demlemek"),
    ("brink", "eşik"),
    ("brisk", "canlı"),
    ("brokerage", "komisyonculuk"),
    ("brood", "kuluçka"),
    ("browse", "göz atmak"),
    ("bruise", "çürük"),
    ("brunt", "en ağır kısım"),
    ("buoyant", "batmayan"),
    ("burgeon", "filizlenmek"),
    ("burrow", "oyuk açmak"),
    ("bustle", "koşuşturma"),
    ("bypass", "yan yola almak"),
    ("bygone", "geçmiş"),
    ("cabin", "kabin"),
    ("cable", "kablo"),
    ("cajole", "ikna etmek"),
    ("calamity", "facia"),
    ("caliber", "kalibre"),
    ("callous", "duyarsız"),
    ("camouflage", "kamuflaj"),
    ("canal", "kanal"),
    ("canopy", "gölgelik"),
    ("candid", "samimi"),
    ("cane", "değnek"),
    ("canny", "zeki"),
    ("capability", "kapasite"),
    ("capacitor", "kondansatör"),
    ("captive", "tutsak"),
    ("caravan", "karavan"),
    ("carbon", "karbon"),
    ("cardinal", "esas"),
    ("caretaker", "bakıcı"),
    ("cargo", "yük"),
    ("carnival", "karnaval"),
    ("carpenter", "marangoz"),
    ("carriage", "fayton"),
    ("cartel", "kartel"),
    ("cashier", "kasiyer"),
    ("castaway", "kıyıya vuran"),
    ("casualty", "kayıp"),
    ("cathedral", "katedral"),
    ("cater", "servis etmek"),
    ("caterpillar", "tırtıl"),
    ("cautious", "dikkatli"),
    ("cease", "son vermek"),
    ("cedar", "sedir"),
    ("celestial", "göksel"),
    ("cellar", "kiler"),
    ("cement", "çimento"),
    ("census", "nüfus sayımı"),
    ("centennial", "yüzüncü yıl"),
    ("ceramic", "seramik"),
    ("cereal", "gevrek"),
    ("certainty", "kesinlik"),
    ("chamber", "oda"),
    ("chaotic", "kaotik"),
    ("charcoal", "odun kömürü"),
    ("charter", "tüzük"),
    ("chasm", "uçurum"),
    ("chatter", "gevezelik"),
    ("chauffeur", "şoför"),
    ("checklist", "kontrol listesi"),
    ("cheerful", "neşeli"),
    ("chef", "aşçı"),
    ("cherish", "değer vermek"),
    ("chew", "çiğnemek"),
    ("chill", "üşümek"),
    ("chime", "çan sesi"),
    ("chimney", "baca"),
    ("chlorine", "klor"),
    ("chore", "ev işi"),
    ("chronicle", "kroniklemek"),
    ("cider", "elma şarabı"),
    ("cipher", "şifre"),
    ("circuit", "devre"),
    ("circulate", "dolaşmak"),
    ("circus", "sirk"),
    ("civic", "vatandaşlıkla ilgili"),
    ("clairvoyant", "geleceği gören"),
    ("clamor", "bağırış"),
    ("clamp", "kelepçelemek"),
    ("clash", "çatışmak"),
    ("clasp", "kavramak"),
    ("clause", "madde"),
    ("clay", "balçık"),
    ("cleanse", "arındırmak"),
    ("clergy", "ruhban sınıfı"),
    ("cliff", "yamaç"),
    ("climate", "iklim"),
    ("clinch", "sağlama almak"),
    ("cloak", "pelerin"),
    ("clockwise", "saat yönünde"),
    ("clog", "tıkamak"),
    ("closet", "dolap"),
    ("clutch", "kavramak"),
    ("coastline", "sahil şeridi"),
    ("cobbler", "ayakkabıcı"),
    ("coerce", "zorlamak"),
    ("coexist", "birlikte yaşamak"),
    ("coffer", "kasa"),
    ("cohesive", "yapışık"),
    ("coil", "sarmak"),
    ("coincide", "çakışmak"),
    ("collaborate", "iş birliği yapmak"),
    ("collage", "kollaj"),
    ("collar", "yaka"),
    ("collateral", "teminat"),
    ("collective", "toplu"),
    ("collide", "çarpışmak"),
    ("colonial", "sömürgeci"),
    ("colony", "sömürge"),
    ("colorful", "renkli"),
    ("combatant", "savaşçı"),
    ("combustion", "yanma"),
    ("comedian", "komedyen"),
    ("comforter", "teselli eden"),
    ("commence", "başlamak"),
    ("commend", "övmek"),
    ("commodity", "emtia"),
    ("commuter", "banliyö sakini"),
    ("compact", "sıkı"),
    ("companion", "arkadaş"),
    ("compassion", "şefkat"),
    ("compel", "zorlamak"),
    ("compensate", "telafi etmek"),
    ("competence", "yeterlilik"),
    ("compile", "derlemek"),
    ("complacent", "rahatına düşkün"),
    ("complement", "tamamlamak"),
    ("compliance", "uyum"),
    ("compose", "oluşturmak"),
    ("compost", "kompost"),
    ("compound", "bileşik"),
    ("compress", "sıkıştırmak"),
    ("comprise", "içermek"),
    ("compulsion", "zorunluluk"),
    ("comrade", "yoldaş"),
    ("conceal", "gizlemek"),
    ("concede", "kabul etmek"),
    ("conceive", "tasarlamak"),
    ("concise", "özlü"),
    ("conducive", "elverişli"),
    ("confer", "görüşmek"),
    ("confide", "güvenmek"),
    ("confine", "sınırlamak"),
    ("conform", "uyum sağlamak"),
    ("confront", "yüzleşmek"),
    ("congestion", "tıkanıklık"),
    ("conjure", "büyü yapmak"),
    ("connectivity", "bağlanabilirlik"),
    ("conqueror", "fetheden"),
    ("conquest", "fetih"),
    ("conscience", "vicdan"),
    ("consecutive", "ardışık"),
    ("consensus", "oy birliği"),
    ("consignment", "emanet sevkiyat"),
    ("consolidate", "sağlamlaştırmak"),
    ("consortium", "konsorsiyum"),
    ("conspire", "komplo kurmak"),
    ("constellation", "yıldız kümesi"),
    ("constitute", "oluşturmak"),
    ("constrain", "zorlama"),
    ("consultant", "danışman"),
    ("consul", "konsolos"),
    ("consumption", "tüketim"),
    ("contagious", "bulaşıcı"),
    ("contaminate", "kirletmek"),
    ("contemplate", "düşünmek"),
    ("contender", "aday"),
    ("contingent", "bağlı"),
    ("contradict", "çelişmek"),
    ("contrary", "zıt"),
    ("contrive", "tasarlamak"),
    ("controller", "kontrolör"),
    ("convene", "toplanmak"),
    ("converge", "birleşmek"),
    ("converse", "sohbet etmek"),
    ("convertible", "dönüştürülebilir"),
    ("convict", "mahkum etmek"),
    ("convoy", "konvoy"),
    ("coolant", "soğutucu"),
    ("cooperate", "iş birliği yapmak"),
    ("coordination", "koordinasyon"),
    ("copier", "fotokopi makinesi"),
    ("copper", "bakır"),
    ("cordial", "samimi"),
    ("cordless", "kablosuz"),
    ("cork", "mantar"),
    ("coronation", "taç giyme"),
    ("corporal", "bedensel"),
    ("correlate", "ilişkilendirmek"),
    ("corridor", "koridor"),
    ("corrode", "aşındırmak"),
    ("cosmic", "kozmik"),
    ("cottage", "kulübe"),
    ("counselor", "danışman"),
    ("counterfeit", "sahte"),
    ("counterpart", "denk"),
    ("countless", "sayısız"),
    ("courtship", "kur yapma"),
    ("coverage", "kapsama"),
    ("coward", "korkak"),
    ("cradle", "beşik"),
    ("craftsman", "zanaatkar"),
    ("cramp", "kramp"),
    ("crane", "vinç"),
    ("crater", "krater"),
    ("crave", "çok arzulamak"),
    ("crawl", "emeklemek"),
    ("credential", "yetki belgesi"),
    ("credible", "güvenilir"),
    ("creed", "inanç"),
    ("crevice", "çatlak"),
    ("cricket", "kriket"),
    ("crimson", "kızıl"),
    ("cripple", "sakatlamak"),
    ("criterion", "kriter"),
    ("crooked", "eğri"),
    ("crossover", "geçiş"),
    ("crowbar", "levye"),
    ("crumb", "ufak parça"),
    ("crunch", "çıtırdamak"),
    ("crusade", "haçlı seferi"),
    ("crust", "kabuk"),
    ("cryptic", "gizemli"),
    ("culminate", "sonuçlanmak"),
    ("culprit", "suçlu"),
    ("cultivate", "işlemek"),
    ("cumulative", "kümülatif"),
    ("cupboard", "dolap"),
    ("curb", "kaldırım kenarı"),
    ("curfew", "sokağa çıkma yasağı"),
    ("curiosity", "merak"),
    ("cursor", "imleç"),
    ("curtail", "kısaltmak"),
    ("cushion", "yastık"),
    ("custody", "velayet"),
    ("cylinder", "silindir"),
    ("cynical", "alaycı"),
    ("dairy", "süt ürünleri"),
    ("damp", "nemli"),
    ("dangle", "sallandırmak"),
    ("daring", "cesur"),
    ("dash", "fırlamak"),
    ("database", "veritabanı"),
    ("dawn", "şafak"),
    ("daylight", "gün ışığı"),
    ("dazzle", "büyülemek"),
    ("deadline", "son teslim tarihi"),
    ("deadlock", "çıkmaz"),
    ("dean", "dekan"),
    ("debris", "enkaz"),
    ("debut", "ilk çıkış"),
    ("decay", "çürümek"),
    ("deceive", "aldatmak"),
    ("decent", "iyi"),
    ("deception", "aldatma"),
    ("decibel", "desibel"),
    ("decisive", "kararlı"),
    ("deck", "güverte"),
    ("decompose", "ayrıştırmak"),
    ("decorate", "süslemek"),
    ("decree", "kararname"),
    ("dedicate", "adamak"),
    ("deduct", "kesinti yapmak"),
    ("deem", "saymak"),
    ("defect", "kusur"),
    ("defiant", "karşı koyan"),
    ("deficiency", "eksiklik"),
    ("deficit", "açık"),
    ("defuse", "etkisiz hale getirmek"),
    ("degrade", "aşağılamak"),
    ("delegate", "delege etmek"),
    ("deliberate", "kasten"),
    ("delicate", "narin"),
    ("delightful", "çok hoş"),
    ("delinquent", "suçlu"),
    ("deliverance", "kurtuluş"),
    ("demeanor", "davranış"),
    ("demolish", "yıkmak"),
    ("demote", "indirmek"),
    ("denim", "kot kumaşı"),
    ("denote", "göstermek"),
    ("density", "yoğunluk"),
    ("dentist", "dişçi"),
    ("depart", "ayrılmak"),
    ("dependable", "güvenilir"),
    ("depict", "betimlemek"),
    ("deplete", "tüketmek"),
    ("deploy", "konuşlandırmak"),
    ("deport", "sınır dışı etmek"),
    ("deposit", "mevduat"),
    ("depot", "depo"),
    ("deprive", "mahrum bırakmak"),
    ("deputy", "vekil"),
    ("derail", "raydan çıkmak"),
    ("derive", "türetmek"),
    ("descend", "inmek"),
    ("descent", "iniş"),
    ("descriptive", "betimleyici"),
    ("designate", "atamak"),
    ("desolate", "ıssız"),
    ("detain", "gözaltına almak"),
    ("detective", "dedektif"),
    ("deter", "caydırmak"),
    ("deteriorate", "kötüleşmek"),
    ("detergent", "temizleyici"),
    ("detour", "yan yol"),
    ("devastate", "harap etmek"),
    ("deviate", "sapmak"),
    ("device", "cihaz"),
    ("devise", "tasarlamak"),
    ("devotee", "taraftar"),
    ("diabetes", "şeker hastalığı"),
    ("diagnose", "teşhis etmek"),
    ("diagram", "şema"),
    ("dialect", "lehçe"),
    ("dialogue", "diyalog"),
    ("diameter", "çap"),
    ("dictate", "dikte etmek"),
    ("differ", "farklı olmak"),
    ("diffuse", "yaymak"),
    ("diligent", "çalışkan"),
    ("dilute", "seyreltmek"),
    ("dim", "sönük"),
    ("dime", "on sent"),
    ("dine", "yemek yemek"),
    ("dioxide", "dioksit"),
    ("diploma", "diploma"),
    ("diplomatic", "diplomatik"),
    ("dire", "vahim"),
    ("directive", "yönerge"),
    ("directory", "dizin"),
    ("disable", "devre dışı bırakmak"),
    ("disarray", "karışıklık"),
    ("disaster", "facia"),
    ("discern", "ayırt etmek"),
    ("discharge", "boşaltmak"),
    ("discipline", "disiplin"),
    ("disclose", "açığa vurmak"),
    ("disconnect", "bağlantıyı kesmek"),
    ("discount", "indirim"),
    ("discourse", "söylev"),
    ("discoverer", "kaşif"),
    ("discreet", "tedbirli"),
    ("discrepancy", "tutarsızlık"),
    ("discretion", "takdir yetkisi"),
    ("discriminate", "ayrım yapmak"),
    ("disguise", "maskelemek"),
    ("dishwasher", "bulaşık makinesi"),
    ("disinfect", "dezenfekte etmek"),
    ("dismissal", "kovma"),
    ("dismount", "inmek"),
    ("disparate", "farklı"),
    ("dispatch", "sevk etmek"),
    ("dispense", "dağıtmak"),
    ("disperse", "dağılmak"),
    ("displace", "yerinden etmek"),
    ("display", "sergilemek"),
    ("displease", "hoşnutsuz etmek"),
    ("disposable", "tek kullanımlık"),
    ("disrupt", "bozmak"),
    ("dissent", "karşı çıkmak"),
    ("distill", "damıtmak"),
    ("distortion", "bozulma"),
    ("distract", "dikkatini dağıtmak"),
    ("distress", "sıkıntı"),
    ("distribute", "dağıtmak"),
    ("district", "ilçe"),
    ("distrust", "güvensizlik"),
    ("diver", "dalgıç"),
    ("divergent", "ayrık"),
    ("diversify", "çeşitlendirmek"),
    ("diversion", "saptırma"),
    ("dividend", "temettü"),
    ("divine", "ilahi"),
    ("divulge", "açıklamak"),
    ("dock", "rıhtım"),
    ("doctrine", "öğreti"),
    ("documentary", "belgesel"),
    ("domain", "alan"),
    ("domestic", "evcil"),
    ("dominate", "hakim olmak"),
    ("donate", "bağışlamak"),
    ("donor", "bağışçı"),
    ("dormitory", "yurt"),
    ("dough", "hamur"),
    ("draft", "taslak"),
    ("dragon", "ejderha"),
    ("drainage", "drenaj"),
    ("dramatic", "dramatik"),
    ("drapery", "perde kumaşı"),
    ("drought", "kuraklık"),
    ("drowsy", "uykulu"),
    ("drummer", "davulcu"),
    ("duct", "kanal"),
    ("dungeon", "zindan"),
    ("duplicate", "çoğaltmak"),
    ("duration", "süre"),
    ("dusk", "alacakaranlık"),
    ("dweller", "sakin"),
    ("dwindle", "azalmak"),
    ("dynamic", "dinamik"),
]


def make_entry(word: str, tr: str, idx: int) -> dict:
    en_sentence = EX_TEMPLATES_EN[idx % len(EX_TEMPLATES_EN)].format(word=word)
    tr_sentence = EX_TEMPLATES_TR[idx % len(EX_TEMPLATES_TR)].format(word_tr=tr)
    return {
        "word": word,
        "cefr": cefr_for(word),
        "tr": tr,
        "example": en_sentence,
        "example_tr": tr_sentence,
    }


def collect_candidates(existing: set) -> list:
    candidates = []
    seen = set(w.lower() for w in existing)

    wiki_data = load_json(WIKI)
    for word, tr in sorted(wiki_data.items()):
        norm = word.strip().lower()
        if not norm or norm.isnumeric() or "/" in norm:
            continue
        if norm in seen:
            continue
        candidates.append((word, tr))
        seen.add(norm)
        if len(candidates) >= NEEDED:
            return candidates

    if len(candidates) < NEEDED:
        full_data = load_json(FULL)
        for word, meta in full_data.items():
            if len(candidates) >= NEEDED:
                break
            norm = word.strip().lower()
            if not norm or norm.isnumeric() or "/" in norm:
                continue
            if norm in seen:
                continue
            tr = meta.get("meaning_tr")
            if not tr:
                continue
            candidates.append((word, tr))
            seen.add(norm)

    if len(candidates) < NEEDED:
        for word, tr in MANUAL_BANK:
            if len(candidates) >= NEEDED:
                break
            norm = word.strip().lower()
            if not norm or norm.isnumeric() or "/" in norm:
                continue
            if norm in seen:
                continue
            candidates.append((word, tr))
            seen.add(norm)

    return candidates


def main():
    data = load_json(TARGET)
    existing_items = data.get("items", [])
    existing_words = {item["word"].lower() for item in existing_items}

    candidates = collect_candidates(existing_words)
    if len(candidates) < NEEDED:
        raise RuntimeError(f"Yeterli yeni kelime bulunamadı: {len(candidates)} < {NEEDED}")

    new_entries = [make_entry(word, tr, idx) for idx, (word, tr) in enumerate(candidates[:NEEDED])]

    # Duplicate kontrolü
    final_words = {item["word"].lower() for item in existing_items}
    truly_new = []
    for entry in new_entries:
        if entry["word"].lower() not in final_words:
            truly_new.append(entry)
            final_words.add(entry["word"].lower())

    data["items"].extend(truly_new)

    with TARGET.open("w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    print(f"Mevcut kelime sayısı (önce): {len(existing_words)}")
    print(f"Eklenen yeni kelime sayısı: {len(truly_new)}")
    print(f"Toplam kelime sayısı (sonra): {len(data['items'])}")


if __name__ == "__main__":
    main()
